POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Vs code vvfdvdfvfd",
    "important": true
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelac",
    "number": "040-123456"
}