POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Vsfм",
    "important": true
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ar",
    "number": "040-7683279859808"
}